KOD-9: added basic layout and game logic
mwiski/battleships pull request #1
Opened 2019-05-11 18:47 UTC by mwiski

2019-05-11 18:48 UTC, mwiski commented
Okno kończące rozgrywkę nie działa tak jak bym chciał, ponieważ otwiera nowe okna zostawiając stare, ale będę nad tym pracował

2019-05-12 21:35 UTC, mwiski commented
Uwaga: dodałem kolejny commit

2019-05-13 08:58 UTC, mps4dev requested changes
Zgłosiłem 20 uwag

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/Main.java
>      public void start(Stage primaryStage) throws Exception {
'throws Exception' zbędne

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/engine/Game.java
> +    private static String title = "Battleships";
`private static final String TITLE`

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/engine/Game.java
> +    public static String getTitle() {
niestatyczna

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/engine/Game.java
> +    private UserInterface gui;
`private final UserInterface gui;`

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/model/Ship.java
>      private int health;
co oznaczać ma `health` czy enum by się nie przydał?

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/model/Ship.java
> +    private boolean vertical = true;
Staramy się nie inicjalizować pól, tym bardziej, że tutaj i tak tę watość nadpisujesz w konstruktorze.

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/gui/Cell.java
> +    private Ship ship = null;
domyślnie na null się i tak ustawia

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/gui/Cell.java
> +    public int x, y;
czemu `public`?

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/gui/PlayerBoard.java
>  public class PlayerBoard extends Parent {
PlayerBoard oraz EnemyBoard mają wiele wspólnego kodu - ja bym wydzielił jakąś klasę abstrakcyjną i po niej podziedziczył

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/gui/UserInterface.java
> +    enum ShipType {
Wydzielić do osobnej klasy/enuma

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/gui/UserInterface.java
> +    private int n = 0;
co to jest `n`?

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/gui/UserInterface.java
> +    private PlayerBoard playerBoard;
spacja przed

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/gui/UserInterface.java
> +    private int shipsToPlace = 8;
co to jest `8`?

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/gui/UserInterface.java
> +        Background background = new Background(backgroundImage);
`return new Background(bakgroundImage);`

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/gui/UserInterface.java
>          Scene startScene = new Scene(layout1, WIDTH, HEIGHT);
`return new scene(...);`

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/gui/UserInterface.java
> +            case 0:
a co to jest case 0, case 1 itp ... ?

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/gui/UserInterface.java
> +        return ship.getHealth() > 0;
lepiej: `isNotAlive(Ship ship)' - moim zdaniem taka metoda powinna być  klasie `Ship`.

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/gui/UserInterface.java
> +    public boolean shootPlayer(Cell cell) {
`private`

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/gui/UserInterface.java
> +    public boolean shootEnemy(Cell cell) {
`private`

2019-05-13 08:58 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/Messages/AlertBox.java
> +public class AlertBox {
`AlertBox` oraz `EndGameBox` mają wspólnego kodu trochę - wydzielić abstrakcję

2019-05-13 17:59 UTC, mwiski commented
Nadałem trochę logiki na poziomie "HARD" komputerowi, ale nie działa wszystko tak jak powinno. Zastanawiam się, czy nie wydzielić metod dotyczących logiki gry z UserInterface i wrzucić je do nowej klasy np. GameLogic.

2019-05-15 07:39 UTC, mps4dev requested changes
:-1:  Wygrałem z komputerem. 
Kosmetyczne poprawki do zrobienia, przede wszystkim duplikację kodu trzeba usunąć i te masakryczne `switch-case`

2019-05-15 07:39 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/Messages/AlertBox.java
> +public class AlertBox extends Box {
bez sensu coś takiego. Czemu metoda `display` jest statyczna? Dziedziczenie nie nadpisuje metod statycznych.
Wspólną część metody z klasy `Box` i` EndGameBox` wydziel do osobnej metody (mówę o liniach 14-22 z klasy `Box`) i dodaj metodę abstrakcyjną `renderContent()`, ktorej implementacja w klasie `EndGameBox` to linie 24-48 zaś w klasie `AlertBox` to linie 23-32 z klasy `Box`. Wówczas mamy w klasie `Box` takie cuś: `public void dispaly(...) { init(); renderContent(); }`

2019-05-15 07:39 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/gui/Board.java
> +    public boolean placeShip(Ship ship, int x, int y) {
metoda powinna być abstrakcyjna i implementacja dostarczona w kasie `EnemyBoard` (w `PlayerBoard` dostarczasz implementację)

2019-05-15 07:39 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/gui/UserInterface.java
> +            case FOUR_MAST:
to jakoś nieładnie wygląda :/ Tym bardziej, że kod w każdym `case` jest identyczny

2019-05-15 07:39 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/gui/UserInterface.java
> +                        n ++;
tutaj tez kod się prawie ciągle powtarza

2019-05-15 07:39 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/Main.java
> +        this.primaryStage = primaryStage;
??? `primaryStage` ma być static? Po co w ogóle to pole? Może to `primaryStage' przekazać w konstruktorze do `UserInterface`

2019-05-15 07:39 UTC, mps4dev requested changes
:-1:

2019-05-20 13:05 UTC, mps4dev requested changes
:-1:

2019-05-20 13:05 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/strategy/PlayerStrategy.java
> +    public boolean shoot(Cell cell, Board board) {
taka sama mtoda jest w drugie strategii ... Może lepiej dać tę metodę jako `default` do interfejsu albo wprowadzić klasę abstrakcyjną zamiast interfejsu.

2019-05-20 21:34 UTC, mps4dev requested changes
Jakoś dziwnie wygląda ustawienie statków przeciwnika (mam 2x5, 2x4, 2x3, 2x2). Czy tak ma być? Na komunikatorze wyślę screena.
Usuń metodę, której nie używasz. 
:-1:

2019-05-20 21:34 UTC, mps4dev commented on src/main/java/pl/wiskim/battleships/strategy/EnemyStrategy.java
>      boolean isEnemyTurn() {
metoda nie używana

2019-05-27 19:37 UTC, merged